-- Create the users2 table
CREATE TABLE IF NOT EXISTS users2 (
    id SERIAL PRIMARY KEY,
    first_name VARCHAR(50),
    last_name VARCHAR(50),
    age INT,
    gender VARCHAR(50),
    nation VARCHAR(50),
    field VARCHAR(100),
    parent_name VARCHAR(100),
    city VARCHAR(100)
);


INSERT INTO users2 (first_name, last_name, age, gender, nation, field, parent_name, city) VALUES
('John', 'Doe', 25, 'Male', 'USA', 'Engineering', 'Jane Doe', 'New York'),
('Alice', 'Smith', 30, 'Female', 'Canada', 'Medicine', 'Robert Smith', 'Toronto'),
('Bob', 'Johnson', 22, 'Male', 'UK', 'Arts', 'Laura Johnson', 'London'),
('Eve', 'Brown', 28, 'Female', 'Germany', 'Science', 'Michael Brown', 'Berlin'),
('Charlie', 'Williams', 35, 'Male', 'France', 'Business', 'Anna Williams', 'Paris'),
('Grace', 'Miller', 27, 'Female', 'Spain', 'Engineering', 'Thomas Miller', 'Madrid'),
('David', 'Davis', 24, 'Male', 'Italy', 'Medicine', 'Sarah Davis', 'Rome'),
('Hannah', 'Martinez', 32, 'Female', 'Japan', 'Arts', 'James Martinez', 'Tokyo'),
('Ivy', 'Garcia', 29, 'Male', 'China', 'Science', 'Patricia Garcia', 'Beijing'),
('Jack', 'Lopez', 26, 'Female', 'India', 'Business', 'Christopher Lopez', 'Mumbai'),
('Liam', 'Wilson', 31, 'Male', 'Brazil', 'Engineering', 'Elizabeth Wilson', 'Rio de Janeiro'),
('Mia', 'Anderson', 23, 'Female', 'Mexico', 'Medicine', 'Anthony Anderson', 'Mexico City'),
('Noah', 'Thomas', 33, 'Male', 'Russia', 'Arts', 'Margaret Thomas', 'Moscow'),
('Olivia', 'Taylor', 34, 'Female', 'South Korea', 'Science', 'Steven Taylor', 'Seoul'),
('Paul', 'Moore', 36, 'Male', 'Australia', 'Business', 'Betty Moore', 'Sydney'),
('Quinn', 'Jackson', 21, 'Female', 'Netherlands', 'Engineering', 'Brian Jackson', 'Amsterdam'),
('Ryan', 'White', 37, 'Male', 'Sweden', 'Medicine', 'Dorothy White', 'Stockholm'),
('Sophie', 'Harris', 38, 'Female', 'Norway', 'Arts', 'Kenneth Harris', 'Oslo'),
('Tyler', 'Martin', 39, 'Male', 'Denmark', 'Science', 'Sandra Martin', 'Copenhagen'),
('Uma', 'Thompson', 40, 'Female', 'Finland', 'Business', 'Kevin Thompson', 'Helsinki'),
('Victor', 'Martinez', 20, 'Male', 'Belgium', 'Engineering', 'Carol Martinez', 'Brussels'),
('Wendy', 'Garcia', 41, 'Female', 'Austria', 'Medicine', 'Edward Garcia', 'Vienna'),
('Xander', 'Rodriguez', 42, 'Male', 'Switzerland', 'Arts', 'Donna Rodriguez', 'Zurich'),
('Yara', 'Lewis', 43, 'Female', 'Ireland', 'Science', 'Mark Lewis', 'Dublin'),
('Zach', 'Lee', 44, 'Male', 'Portugal', 'Business', 'Nancy Lee', 'Lisbon'),
('Amy', 'Walker', 45, 'Female', 'Greece', 'Engineering', 'George Walker', 'Athens'),
('Ben', 'Hall', 46, 'Male', 'Turkey', 'Medicine', 'Michelle Hall', 'Istanbul'),
('Cara', 'Young', 47, 'Female', 'Israel', 'Arts', 'Richard Young', 'Tel Aviv'),
('Dan', 'Allen', 48, 'Male', 'Egypt', 'Science', 'Barbara Allen', 'Cairo'),
('Eva', 'King', 49, 'Female', 'South Africa', 'Business', 'Charles King', 'Cape Town'),
('Finn', 'Wright', 50, 'Male', 'Nigeria', 'Engineering', 'Shirley Wright', 'Lagos'),
('Gina', 'Scott', 22, 'Female', 'Kenya', 'Medicine', 'David Scott', 'Nairobi'),
('Harry', 'Adams', 23, 'Male', 'Ghana', 'Arts', 'Deborah Adams', 'Accra'),
('Isla', 'Nelson', 24, 'Female', 'Uganda', 'Science', 'Jason Nelson', 'Kampala'),
('Jake', 'Carter', 25, 'Male', 'Tanzania', 'Business', 'Angela Carter', 'Dar es Salaam'),
('Kara', 'Mitchell', 26, 'Female', 'Ethiopia', 'Engineering', 'Matthew Mitchell', 'Addis Ababa'),
('Luke', 'Perez', 27, 'Male', 'Morocco', 'Medicine', 'Sharon Perez', 'Rabat'),
('Mila', 'Roberts', 28, 'Female', 'Algeria', 'Arts', 'Patrick Roberts', 'Algiers'),
('Nate', 'Turner', 29, 'Male', 'Tunisia', 'Science', 'Emma Turner', 'Tunis'),
('Olga', 'Phillips', 30, 'Female', 'Libya', 'Business', 'Samuel Phillips', 'Tripoli'),
('Pete', 'Campbell', 31, 'Male', 'Sudan', 'Engineering', 'Judith Campbell', 'Khartoum'),
('Quincy', 'Parker', 32, 'Female', 'Senegal', 'Medicine', 'Alexander Parker', 'Dakar'),
('Rose', 'Evans', 33, 'Male', 'Mali', 'Arts', 'Ruth Evans', 'Bamako'),
('Steve', 'Edwards', 34, 'Female', 'Zambia', 'Science', 'Betty Edwards', 'Lusaka'),
('Tina', 'Collins', 35, 'Male', 'Zimbabwe', 'Business', 'Harold Collins', 'Harare'),
('Umar', 'Stewart', 36, 'Female', 'Botswana', 'Engineering', 'Jerry Stewart', 'Gaborone'),
('Vera', 'Sanchez', 37, 'Male', 'Namibia', 'Medicine', 'Rebecca Sanchez', 'Windhoek'),
('Will', 'Morris', 38, 'Female', 'Mozambique', 'Arts', 'Peter Morris', 'Maputo'),
('Xena', 'Murphy', 39, 'Male', 'Angola', 'Science', 'Kathleen Murphy', 'Luanda'),
('Yves', 'Cook', 40, 'Female', 'Madagascar', 'Business', 'Douglas Cook', 'Antananarivo');


